config/routes.rb
R7::Application.routes.draw do
  resources :high_scores
 resources :worksheets

  resources :class_assignments

  resources :student_assignments

  resources :assignments

  resources :op_timers

  resources :schools

  resources :class_lists

  resources :teachers

  resources :gift_certs

  resources :discount_codes

  resources :agcommisions

  resources :commisions

  resources :agents

  resources :admins

  resources :parents

  resources :weekly_activity_summaries

  resources :topic_run_results

  resources :topic_activity_summaries
  resources :students
  resources :topics
  resources :users
  resources :sessions do end
resources :users
resource :session  do end
  
  match  'createFamilyAccount', :to => 'users#createFamilyAccount'
match  'signup2', :to => 'users#new'
match  'login', :to => 'sessions#new'
match  'logout', :to => 'sessions#destroy'
match  'activateParentAccount', :to => 'sessions#activateParentAccount'
match  'resendActivationCode', :to => 'sessions#resendActivationCode'
match  'contactUs', :to => 'sessions#contactUs'
match  'logClientError', :to => 'sessions#logClientError'
match  'forgottenPassword', :to => 'sessions#forgottenPassword'
match  'getAllStudentLoginData', :to => 'sessions#getAllStudentLoginData'

match  'checkForExistingSession', :to => 'sessions#new'
match  'updateStudent', :to => 'students#update'
match  'updateStudentStatus', :to => 'students#updateStatus'
match  'changePassword', :to => 'users#changePassword'
match  'updateParent', :to => 'parents#update'
match  'updateUserStatus', :to => 'users#updateStatus'

match 'getFotdFile', :to => 'sessions#getFotdFile'

match  'getStudents', :to => 'admins#getStudents'
match  'getParents', :to => 'admins#getParents'
match  'deleteParent', :to => 'admins#deleteParent'
match  'coaxParent', :to => 'admins#coaxParent'
match  'activateParent', :to => 'admins#activateParent'
match  'createSchool', :to => 'admins#createSchool'
    

match  'getAgentParents', :to => 'agents#getAgentParents'
match  'getAgents', :to => 'agents#getAgents'
match  'updateAgent', :to => 'agents#update'

match  'deleteTeacher', :to => 'teachers#deleteTeacher'
match  'updateTeacher', :to => 'teachers#updateTeacher'
match  'addTeacher', :to => 'teachers#addTeacher'
match  'getTeachers', :to => 'teachers#getTeachers'
match  'getStudentsForClass', :to => 'teachers#getStudentsForClass'
match  'addStudentForSchool', :to => 'teachers#addStudentForSchool'
match  'getWeeklyActivityForClass', :to => 'teachers#getWeeklyActivityForClass'
match  'deleteStudent', :to => 'teachers#deleteStudent'

match  'updateClass', :to => 'class_lists#updateClass'
match  'deleteClass', :to => 'class_lists#deleteClass'
match  'addClass', :to => 'class_lists#addClass'

match  'getStudentsForClassAssignment', :to => 'student_assignments#getStudentsForClassAssignment'

match  'updateSchool', :to => 'schools#updateSchool'

match  'getAgentCommisions', :to => 'Agcommisions#getAgentCommisions'
match  'updateCommision', :to => 'agcommisions#updateCommision'
match  'addCommisionFromSubagent', :to => 'agcommisions#addCommisionFromSubagent'

match  'redeem', :to => 'gift_certs#redeem'

  match ':controller(/:action(/:id(.:format)))'

  match '/test' => 'high_scores#test', :as => :test

end

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= error_messages_for :admin %>

<% form_for(@admin) do |f| %>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<h1>Listing admins</h1>

<table>
  <tr>
  </tr>

<% for admin in @admins %>
  <tr>
    <td><%= link_to 'Show', admin %></td>
    <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
    <td><%= link_to 'Destroy', admin, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= error_messages_for :admin %>

<% form_for(@admin) do |f| %>
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>