config/routes.rb
R7::Application.routes.draw do
  resources :high_scores
 resources :worksheets

  resources :class_assignments

  resources :student_assignments

  resources :assignments

  resources :op_timers

  resources :schools

  resources :class_lists

  resources :teachers

  resources :gift_certs

  resources :discount_codes

  resources :agcommisions

  resources :commisions

  resources :agents

  resources :admins

  resources :parents

  resources :weekly_activity_summaries

  resources :topic_run_results

  resources :topic_activity_summaries
  resources :students
  resources :topics
  resources :users
  resources :sessions do end
resources :users
resource :session  do end
  
  match  'createFamilyAccount', :to => 'users#createFamilyAccount'
match  'signup2', :to => 'users#new'
match  'login', :to => 'sessions#new'
match  'logout', :to => 'sessions#destroy'
match  'activateParentAccount', :to => 'sessions#activateParentAccount'
match  'resendActivationCode', :to => 'sessions#resendActivationCode'
match  'contactUs', :to => 'sessions#contactUs'
match  'logClientError', :to => 'sessions#logClientError'
match  'forgottenPassword', :to => 'sessions#forgottenPassword'
match  'getAllStudentLoginData', :to => 'sessions#getAllStudentLoginData'

match  'checkForExistingSession', :to => 'sessions#new'
match  'updateStudent', :to => 'students#update'
match  'updateStudentStatus', :to => 'students#updateStatus'
match  'changePassword', :to => 'users#changePassword'
match  'updateParent', :to => 'parents#update'
match  'updateUserStatus', :to => 'users#updateStatus'

match 'getFotdFile', :to => 'sessions#getFotdFile'

match  'getStudents', :to => 'admins#getStudents'
match  'getParents', :to => 'admins#getParents'
match  'deleteParent', :to => 'admins#deleteParent'
match  'coaxParent', :to => 'admins#coaxParent'
match  'activateParent', :to => 'admins#activateParent'
match  'createSchool', :to => 'admins#createSchool'
    

match  'getAgentParents', :to => 'agents#getAgentParents'
match  'getAgents', :to => 'agents#getAgents'
match  'updateAgent', :to => 'agents#update'

match  'deleteTeacher', :to => 'teachers#deleteTeacher'
match  'updateTeacher', :to => 'teachers#updateTeacher'
match  'addTeacher', :to => 'teachers#addTeacher'
match  'getTeachers', :to => 'teachers#getTeachers'
match  'getStudentsForClass', :to => 'teachers#getStudentsForClass'
match  'addStudentForSchool', :to => 'teachers#addStudentForSchool'
match  'getWeeklyActivityForClass', :to => 'teachers#getWeeklyActivityForClass'
match  'deleteStudent', :to => 'teachers#deleteStudent'

match  'updateClass', :to => 'class_lists#updateClass'
match  'deleteClass', :to => 'class_lists#deleteClass'
match  'addClass', :to => 'class_lists#addClass'

match  'getStudentsForClassAssignment', :to => 'student_assignments#getStudentsForClassAssignment'

match  'updateSchool', :to => 'schools#updateSchool'

match  'getAgentCommisions', :to => 'Agcommisions#getAgentCommisions'
match  'updateCommision', :to => 'agcommisions#updateCommision'
match  'addCommisionFromSubagent', :to => 'agcommisions#addCommisionFromSubagent'

match  'redeem', :to => 'gift_certs#redeem'

  match ':controller(/:action(/:id(.:format)))'

  match '/test' => 'high_scores#test', :as => :test

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  
  validates_presence_of :no_of_problems, :no_of_rows, :no_of_cols
  validates_length_of :display_label, :within => 4..20
  validates_length_of :problem_generator_class, :within => 3..40
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
   
   before_filter :login_required
   
   
  # GET /topics
  # GET /topics.xml
  def index
    @topics = Topic.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.xml
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.xml
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.xml
  # create a new Topic record
  def create
    
     begin
        @topic = Topic.new(params[ "topic" ])    
     rescue Exception => e    
        respond_to do |format|
          format.xml  { render :xml => errorRsp( e.message) }
        end
      return
    end
    
       
    logger.info  log_hash "Topic", @topic.attributes
    
     # noting fatal happened with the 'new'
    respond_to do |format|
      begin 
        if @topic.save
          format.xml  { render :xml => successRsp }
        else
          format.xml  { render :xml => errorRsp( @topic.errors.to_xml ) }
        end
      rescue Exception => e    
        format.xml  { render :xml => errorRsp( "xx-" + e.message ) }
      end
    end
  end

  
  # PUT /topics/1
  # PUT /topics/1.xml
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        flash[:notice] = 'Topic was successfully updated.'
        format.html { redirect_to(@topic) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.xml
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to(topics_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= error_messages_for :topic %>

<% form_for(@topic) do |f| %>
  <p>
    <b>Topicid</b><br />
    <%= f.text_field :topicId %>
  </p>

  <p>
    <b>Noofproblems</b><br />
    <%= f.text_field :noOfProblems %>
  </p>

  <p>
    <b>Noofrows</b><br />
    <%= f.text_field :noOfRows %>
  </p>

  <p>
    <b>Noofcols</b><br />
    <%= f.text_field :noOfCols %>
  </p>

  <p>
    <b>Displaylabel</b><br />
    <%= f.text_field :displayLabel %>
  </p>

  <p>
    <b>Fulldesciption</b><br />
    <%= f.text_field :fullDesciption %>
  </p>

  <p>
    <b>Problemgeneratorclass</b><br />
    <%= f.text_field :problemGeneratorClass %>
  </p>

  <p>
    <b>Parameters</b><br />
    <%= f.text_field :parameters %>
  </p>

  <p>
    <b>Maxtimeinsec</b><br />
    <%= f.text_field :maxTimeInSec %>
  </p>

  <p>
    <b>Problemviewctlclass</b><br />
    <%= f.text_field :problemViewCtlClass %>
  </p>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <tr>
    <th>Topicid</th>
    <th>Noofproblems</th>
    <th>Noofrows</th>
    <th>Noofcols</th>
    <th>Displaylabel</th>
    <th>Fulldesciption</th>
    <th>Problemgeneratorclass</th>
    <th>Parameters</th>
    <th>Maxtimeinsec</th>
    <th>Problemviewctlclass</th>
  </tr>

<% for topic in @topics %>
  <tr>
    <td><%=h topic.topicId %></td>
    <td><%=h topic.noOfProblems %></td>
    <td><%=h topic.noOfRows %></td>
    <td><%=h topic.noOfCols %></td>
    <td><%=h topic.displayLabel %></td>
    <td><%=h topic.fullDesciption %></td>
    <td><%=h topic.problemGeneratorClass %></td>
    <td><%=h topic.parameters %></td>
    <td><%=h topic.maxTimeInSec %></td>
    <td><%=h topic.problemViewCtlClass %></td>
    <td><%= link_to 'Show', topic %></td>
    <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
    <td><%= link_to 'Destroy', topic, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= error_messages_for :topic %>

<% form_for(@topic) do |f| %>
  <p>
    <b>Topicid</b><br />
    <%= f.text_field :topicId %>
  </p>

  <p>
    <b>Noofproblems</b><br />
    <%= f.text_field :noOfProblems %>
  </p>

  <p>
    <b>Noofrows</b><br />
    <%= f.text_field :noOfRows %>
  </p>

  <p>
    <b>Noofcols</b><br />
    <%= f.text_field :noOfCols %>
  </p>

  <p>
    <b>Displaylabel</b><br />
    <%= f.text_field :displayLabel %>
  </p>

  <p>
    <b>Fulldesciption</b><br />
    <%= f.text_field :fullDesciption %>
  </p>

  <p>
    <b>Problemgeneratorclass</b><br />
    <%= f.text_field :problemGeneratorClass %>
  </p>

  <p>
    <b>Parameters</b><br />
    <%= f.text_field :parameters %>
  </p>

  <p>
    <b>Maxtimeinsec</b><br />
    <%= f.text_field :maxTimeInSec %>
  </p>

  <p>
    <b>Problemviewctlclass</b><br />
    <%= f.text_field :problemViewCtlClass %>
  </p>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p>
  <b>Topicid:</b>
  <%=h @topic.topicId %>
</p>

<p>
  <b>Noofproblems:</b>
  <%=h @topic.noOfProblems %>
</p>

<p>
  <b>Noofrows:</b>
  <%=h @topic.noOfRows %>
</p>

<p>
  <b>Noofcols:</b>
  <%=h @topic.noOfCols %>
</p>

<p>
  <b>Displaylabel:</b>
  <%=h @topic.displayLabel %>
</p>

<p>
  <b>Fulldesciption:</b>
  <%=h @topic.fullDesciption %>
</p>

<p>
  <b>Problemgeneratorclass:</b>
  <%=h @topic.problemGeneratorClass %>
</p>

<p>
  <b>Parameters:</b>
  <%=h @topic.parameters %>
</p>

<p>
  <b>Maxtimeinsec:</b>
  <%=h @topic.maxTimeInSec %>
</p>

<p>
  <b>Problemviewctlclass:</b>
  <%=h @topic.problemViewCtlClass %>
</p>


<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>